# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('maker', models.CharField(max_length=30)),
                ('date_made', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pages', models.IntegerField()),
                ('title', models.CharField(max_length=30)),
                ('composer', models.CharField(max_length=30)),
                ('date_pub', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('est_price', models.IntegerField()),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(max_length=30)),
                ('date_made', models.DateField()),
                ('description', models.CharField(max_length=120)),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicianModels.Object')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag_type', models.CharField(max_length=15)),
                ('objects', models.ManyToManyField(to='MusicianModels.Object')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicianModels.User'),
        ),
        migrations.AddField(
            model_name='music',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicianModels.Object'),
        ),
        migrations.AddField(
            model_name='instr',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MusicianModels.Object'),
        ),
    ]
