# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicianModels', '0002_auto_20170418_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='objects',
            field=models.ManyToManyField(blank=True, to='MusicianModels.Object'),
        ),
    ]
