# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-24 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicianModels', '0003_auto_20170423_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='objects',
            field=models.ManyToManyField(to='MusicianModels.Object'),
        ),
    ]
