# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-27 23:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MusicianModels', '0006_auto_20170427_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='objects',
        ),
        migrations.AddField(
            model_name='object',
            name='post',
            field=models.BooleanField(default=datetime.datetime(2017, 4, 27, 23, 10, 55, 118727, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='tags',
            field=models.ManyToManyField(blank=True, to='MusicianModels.Tag'),
        ),
        migrations.AlterField(
            model_name='object',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 27, 23, 10, 47, 919316, tzinfo=utc)),
        ),
    ]
