# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-27 23:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MusicianModels', '0007_auto_20170427_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 4, 27, 23, 13, 0, 347163, tzinfo=utc)),
        ),
    ]
